ecom/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ecomapp.urls")),

]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
#fetching static files to html files
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"

urlpatterns = [


# Client Home View
	path("", ClientHomeView.as_view(), name = 'clienthome'),

	path("category/<slug:slug>/", 
		CategoryDetailView.as_view(), name = 'categorydetail'),


	path("add-to-cart/<int:pk>/",
		AddToCartView.as_view(), name = "addtocart"),

	path("cart/", CartView.as_view(), name = 'cart'),

	path("manage-cart/<int:pk>/<action>/", 
		ManageCartView.as_view(), name = 'managecart'),

	path("empty-cart/", 
		EmptyCartView.as_view(), name = 'emptycart'),

	path("customer/sign-up/", CustomerSignupView.as_view(), name = 'customersignup'),
	path("customer/login/", CustomerLoginView.as_view(), name = 'customerlogin'),


	# Signin Url Start
	path("ecom-admin/signin/", AdminSigninView.as_view(), name = 'adminsignin'),
	path("ecom-admin/signout/", AdminSignoutView.as_view(), name = 'adminsignout'),


    path("search/", SearchView.as_view(), name = "search"),
    path("customer-search/", ClientSearchView.as_view(), name = "clientsearch"),

    path("ajaxsearch/", AjaxSearchView.as_view(), name = "ajaxsearch"),

    path("order/", OrderCreateView.as_view(), name = "ordercreate"),




#*************************
#*************************
#*************************
#*************************
#*************************


	# Admin Url Starts

	#Admin home view
	path("ecom-admin/", AdminHomeView.as_view(), name = 'adminhome'),

	path("ecom-admin/product/list/", AdminProductListView.as_view(), name = 'adminproductlist'),

	path("ecom-admin/cart/list/", AdminCartListView.as_view(), name = 'admincartlist'),

	path("ecom-admin/cart/<int:pk>/detail/", 
		AdminCartDetailView.as_view(), name = 'admincartdetail'),

	path("ecom-admin/product/<int:pk>/detail/", 
		AdminProductDetailView.as_view(), name = 'adminproductdetail'),

	path("ecom-admin/order/list/", AdminOrderList.as_view(), name = 'adminorderlist'),

	path("ecom-admin/order/<int:pk>/detail", AdminOrderDetailView.as_view(), name = "adminorderdetail"),

	


	
]

templates/clienttemplates/cart.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Cart Detail
{% endblock %}


{% block content %}

<h3>My Cart</h3>
<img src="{% static 'clientstatic/images/buddha.jpg' %}" width="80" id="myp">
<button type="btn" id="empty-cart" href="{% url 'ecomapp:emptycart' %}">Empty cart</button>
<div id="my-content">
	<table class="table" id="my-table">
		<thead>
			<tr>
				<th>SN</th>
				<th>Product</th>
				<th>Image</th>
				<th>Rate</th>
				<th>Quantity</th>
				<th>Subtotal</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for cartproduct in mycart.cartproduct_set.all %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{cartproduct.product.title}}</td>
				<td><img src="{{cartproduct.product.image.url}}" alt="product" width="75"></td>
				<td>{{cartproduct.rate}}</td>
				<td>{{cartproduct.quantity}}</td>
				<td>{{cartproduct.subtotal}}</td>
				<td>
					<button class="cart-manage" type="btn" href="{% url 'ecomapp:managecart' cartproduct.id 'inr' %}"> +</button>
					<button type="button" href="{% url 'ecomapp:managecart' cartproduct.id 'dcr' %}" class="cart-manage">-</button>
					<button type="btn" href="{% url 'ecomapp:managecart' cartproduct.id 'rmv' %}" class="cart-manage">x</button>
				</td>
			</tr>
			{% empty %}
			<tr>
				<td colspan="5" class="text-center">No product exists in cart <a href="{% url 'ecomapp:clienthome' %}">Shop Now</a></td>
			</tr>
			{% endfor %}
			<tr>
				<th colspan="5" class="text-right">Total: </th>
				<th>{{mycart.total}}</th>
			</tr>
		</tbody>
		
	</table>
</div>
<a href="{% url 'ecomapp:ordercreate' %}">Check Out Now</a>


{% endblock %}

{% block js %}


	<script type="text/javascript">
		$(document).ready(function(){
			$(".cart-manage").on("click", function(){
				$("#my-content").on("click", ".cart-manage", function(){
				var url_end_point = $(this).attr("href");
				$.ajax({
					method: 'get',
					url: url_end_point,
					data: {

					},
					success: function(data){
						$("#my-content").load("#my-content #my-table");
						$('#myp').html(data).css("display", 'block');
						setTimeout(fade_out, 5000);
							function fade_out() {
						$("#myp").fadeOut().empty();
						}
					}
				})
			  })
			})
		})
	</script>

	<script>
	    $(document).ready(function(){ 
	        $("#empty-cart").on("click", function(){
				var empty_url = $(this).attr("href");
				$.ajax({
					method: 'get',
					url: empty_url,
					data: {

					},
					success: function(data){
						$("#my-content").load("#my-content #my-table");

					}
				});
			});
		});
	</script>

{% endblock %}

templates/clienttemplates/clientaddtocart.html
<h3>Product added to cart.</h3>

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'clientstatic/css/bootstrap.min.css' %}">
	<script src="{% static 'clientstatic/js/jquery-3.4.1.min.js' %}"></script>
	
<!-- Jquery Begins-->
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
 <!-- Jquery script ends -->
</head>
<body class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<a href="{% url 'ecomapp:clienthome' %}">Home</a>
			<a href="{% url 'ecomapp:cart' %}">Mycart</a>
			{% if request.user.is_authenticated %}
			<a href=" {% url 'ecomapp:adminhome' %} ">{{request.user.username}}</a>
			<a href="/ecom-admin/signout/">Logout</a>
			{% else %}
			<a href="{% url 'ecomapp:customersignup' %}">Signup</a>
			<a href="{% url 'ecomapp:customerlogin' %}">LogIn</a>
			{% endif %}
		</div>
		<div class="col-md-4">
			<form method="GET" action="/customer-search/">
				<input type="text" name="query" placeholder="Search Products..." value="{{request.GET.query}}"
				 id="txtSearch">
				<button>Submit</button>
			</form>
		</div>
	</div>

	<div class="row">
		<div class="col-md-3">
			<h3>Categories</h3><hr>
			{% for cat in root_categories %}
			<li><a href="{% url 'ecomapp:categorydetail' cat.slug %}">{{cat.title}}</a></li>
				{% for subcat in cat.productcategory_set.all %}
				<li class="ml-5"><a href="{% url 'ecomapp:categorydetail' subcat.slug %}">{{subcat.title}}</a></li>
				{% endfor %}
			{% endfor %}
			
		</div>
		<div class="col-md-9">
			{% block content %}
			{% endblock %}
			<script>
			    $(document).ready(function(){ 
			        $("#txtSearch").on("keyup", function(){
			            var keyword = $(this).val();
			            $.ajax({
			              method: "get",
			              url:"{% url 'ecomapp:ajaxsearch' %}",
			              data:{
			                "query": keyword,
			              },
			              success: function(data) {
			                  $("#txtSearch").autocomplete({
			                    source: data.results
			                  });
			                } 
			        	});
			    	});
				});
			</script>

		</div>
	</div>
{% block js %}
{% endblock %}

	<script type="text/javascript">
		$(document).ready(function(){
			$(".add-to-cart").on("click", function(){
				var url_end_point = $(this).attr("data-href");
				$.ajax({
					method: 'get',
					url: url_end_point,
					data: {

					},
					success: function(){
						alert("item added to cart")
					}
				})
			})
		})
	</script>

</body>
</html>

templates/clienttemplates/clientcategorydetail.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Client Category Detail Page 
{% endblock %}


{% block content %}

<h5 class="text-info">Category: {{ categoryobject.title }}</h5>
<h3>All Products</h3>


<div class="row">
	{% for product in categoryobject.product_set.all %}
	<div class="col-md-3">
		<h5 class="">{{product.title}}</h5>
		<img src="{{product.image.url}}" alt='product' class="img-fluid">
		<p>Price: <strike>Rs. {{product.mrp}}</strike> Rs. {{product.sp}}</p>
		<button class="add-to-cart" type="btn" data-href="{% url 'ecomapp:addtocart' product.id %}">Add to Cart</button>
	</div>
	{% endfor %}
</div>


{% for subcat in categoryobject.productcategory_set.all %}
<h4 class="text-info">{{subcat.title}}</h4>
<div class="row">
	{% for product in subcat.product_set.all %}
	<div class="col-md-3">
		<h5>{{product.title}}</h5>
		<img src="{{product.image.url}}" alt='product' class="img-fluid">
		<p>Price: <strike>Rs. {{product.mrp}}</strike> Rs. {{product.sp}}</p>
		<button class="add-to-cart" type="btn" data-href="{% url 'ecomapp:addtocart' product.id %}">Add to Cart</button>
	</div>
	{% endfor %}
</div>


{% endfor %}



{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Client Home Page
{% endblock %}



{% block content %}
<h3>All Products</h3><hr>
<div class="row">
	{% for product in allproducts %}
	<div class="col-md-3">
		<h5>{{product.title}}</h5>
		<!-- {% if product.image %} -->
		<img src="{{product.image.url}}" alt='product' class="img-fluid">
		<!-- {% endif %} -->
		<p>Price: <strike>Rs. {{product.mrp}}</strike> Rs. {{product.sp}}</p>
		<button class="add-to-cart" type="btn" data-href="{% url 'ecomapp:addtocart' product.id %}">Add to Cart</button>
	</div>
	{% endfor %}
</div>

{% endblock %}

templates/clienttemplates/clientmanagecart.html
<h4>
	{{message}}
</h4>

templates/clienttemplates/clientsearch.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Customer Search Results
{% endblock %}


{% block content %}
<div class="row">
	<h3>Search Results On: "<span>{{request.GET.query}}</span>"</h3>
	<hr>
	<hr>
</div>

{% if allproducts.has_other_pages %}
<ul class="pagination">
	{% if allproducts.has_previous %}
	<li class="page-item"><a class="page-link" href="?page={{ allproducts.previous_page_number }}&query={{request.GET.query}}">Previous</a></li>
	{% else %}
	<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	{% endif %}
	{% for n in allproducts.paginator.page_range %}
		{% if allproducts.number == n %}
			<li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
		{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ n }}&query={{request.GET.query}}">{{n}}</a></li>
		{% endif %}
	{% endfor %}
	{% if allproducts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ allproducts.next_page_number}}&query={{request.GET.query}}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
</ul>
{% endif %}
<div class="row">
	{% for search in allproducts %}
		<div class="col-md-3">
			<img class="card-img-top" src="{{ search.image.url }}" width="250" height="200">
			<div class="card-body bg-light text-center">
			<h5 class="card-title ">{{ search.title }}</h5>
			<p class="card-text mb-3 ">Price: Rs.{{ search.sp }}/-</p>
			<p>{{search.category.title}}</p>
			<a href="{% url 'ecomapp:adminproductdetail' search.id %}">view more</a>
			</div>
		</div>
		<hr>
		{% empty %}
		<div class="col-md-3">
			<p class="card-text mb-3 ">No results found</p>
		</div>
	{% endfor %}

</div>



{% endblock %}

templates/clienttemplates/customerlogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
	Ecom-Customer Login Page		
	</title>
</head>
<body class="container-fluid">

<div class="row">
	<div class="col-md-6 mx-auto">
		<h4>Customer Signin Form</h4><hr>
		<form method="post">
			{% if error %}
			<li class="text-danger">{{error}}</li>
			{% endif %}
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" name="Login" class="btn btn-info">		
		</form>	
	</div>
</div>





</body>
</html>

templates/clienttemplates/customersignup.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Customer Signup Form
{% endblock %}


{% block content %}

<div class="row">
	<div class="col-md-6 mx-auto">
		<h4>Customer Signup Form</h4><hr>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{{cform.as_p}}
			<input type="submit" name="Signup" class="btn btn-info">		
		</form>	
	</div>
</div>


{% endblock %}

templates/clienttemplates/ordercreate.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Client Order Create Page
{% endblock %}


{% block content %}

	<h4><span>Your Order Form</span></h4><hr>
	<div class="row">

		<div class="col-md-6">
			<h4><span>Your Cart Order List</span></h4>
			<table class="table">
				<thead>
					<tr>
						<th>SN</th>
						<th>Product</th>
						<th>Subtotal</th>
					</tr>
				</thead>
				<tbody>
					{% for cartproduct in cart_obj.cartproduct_set.all %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{cartproduct.product.title}}</td>
						<td>{{cartproduct.rate}}*{{cartproduct.quantity}} = {{cartproduct.subtotal}}</td>
					</tr>
					{% endfor %}
					<tr>
						<th colspan="2" class="text-right">Total: </th>
						<th>{{cart_obj.total}}</th>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="col-md-6">
			<form method="post">
				{% csrf_token %}
				{{form.as_p}}
				<input type="submit" name="Send Order">		
			</form>	
		</div>

	</div>

{% endblock %}