ecom/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ecomapp.urls")),

]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
#fetching static files to html files
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path
from .views import *

app_name = "ecomapp"

urlpatterns = [


# Client Home View
	path("", ClientHomeView.as_view(), name = 'clienthome'),

	path("category/<slug:slug>/", 
		CategoryDetailView.as_view(), name = 'categorydetail'),


	path("add-to-cart/<int:pk>/",
		AddToCartView.as_view(), name = "addtocart"),

	path("cart/", CartView.as_view(), name = 'cart'),

	path("manage-cart/<int:pk>/<action>/", 
		ManageCartView.as_view(), name = 'managecart'),

	path("empty-cart/", 
		EmptyCartView.as_view(), name = 'emptycart'),

	path("customer/sign-up/", CustomerSignupView.as_view(), name = 'customersignup'),
	path("customer/login/", CustomerLoginView.as_view(), name = 'customerlogin'),


	# Signin Url Start
	path("ecom-admin/signin/", AdminSigninView.as_view(), name = 'adminsignin'),
	path("ecom-admin/signout/", AdminSignoutView.as_view(), name = 'adminsignout'),


    path("search/", SearchView.as_view(), name = "search"),
    path("customer-search/", ClientSearchView.as_view(), name = "clientsearch"),

    path("ajaxsearch/", AjaxSearchView.as_view(), name = "ajaxsearch"),

    path("order/", OrderCreateView.as_view(), name = "ordercreate"),




#*************************
#*************************
#*************************
#*************************
#*************************


	# Admin Url Starts

	#Admin home view
	path("ecom-admin/", AdminHomeView.as_view(), name = 'adminhome'),

	path("ecom-admin/product/list/", AdminProductListView.as_view(), name = 'adminproductlist'),

	path("ecom-admin/cart/list/", AdminCartListView.as_view(), name = 'admincartlist'),

	path("ecom-admin/cart/<int:pk>/detail/", 
		AdminCartDetailView.as_view(), name = 'admincartdetail'),

	path("ecom-admin/product/<int:pk>/detail/", 
		AdminProductDetailView.as_view(), name = 'adminproductdetail'),

	path("ecom-admin/order/list/", AdminOrderList.as_view(), name = 'adminorderlist'),

	path("ecom-admin/order/<int:pk>/detail", AdminOrderDetailView.as_view(), name = "adminorderdetail"),

	


	
]

templates/admintemplates/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<link rel="stylesheet" type="text/css" href="{% static 'clientstatic/css/bootstrap.min.css' %}">
	<script src="{% static 'clientstatic/js/jquery-3.4.1.min.js' %}"></script>

<!-- Jquery Begins-->
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
 <!-- Jquery script ends -->
</head>
<body class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<a href="{% url 'ecomapp:clienthome' %}">Client-Home</a>
			<a href="{% url 'ecomapp:adminhome' %}">Admin-Home</a>
			{% if request.user.is_authenticated %}
			<a href=""><span>{{request.user.username}}</span></a>
			<a href="/ecom-admin/signout/"><span>Logout</span></a>
			{% endif %}
		</div>
		<div class="col-md-4">
			<form method="GET" action="/search/">
				<input type="text" name="query" placeholder="Search Products..." value="{{request.GET.query}}"
				 id="txtSearch">
				<button>Submit</button>
			</form>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2">
			<h3>Admin Panel</h3><hr>

			<li><a href="{% url 'ecomapp:admincartlist' %}">Cart List</a></li>			
			<li><a href="{% url 'ecomapp:adminproductlist' %}">Products</a></li>			
			<li><a href="{% url 'ecomapp:adminorderlist' %}">Orders</a></li>			
		</div>
		
		<div class="col-md-10">
			
		{% block content %}
		{% endblock %}

			<script>
			    $(document).ready(function(){ 
			        $("#txtSearch").on("keyup", function(){
			            var keyword = $(this).val();
			            $.ajax({
			              method: "get",
			              url:"{% url 'ecomapp:ajaxsearch' %}",
			              data:{
			                "query": keyword,
			              },
			              success: function(data) {
			                  $("#txtSearch").autocomplete({
			                    source: data.results
			                  });
			                } 
			        	});
			    	});
				});
			</script>

		</div>		
</body>
</html>

templates/admintemplates/admincartdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Cart Detail Page
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<h3 class="text-success">Detail of Cart ID: {{cartobject.id}}</h3>
	</div>
	<div class="col-md-6">
		<h3 class="text-primary">Order Status: </h3>
	</div>
</div>

<table class="table">
	<thead>
		<tr>
			<th>SN</th>
			<th>Product</th>
			<th>Image</th>
			<th>Rate</th>
			<th>Quantity</th>
			<th>Date Created</th>
			<th>Subtotal</th>
		</tr>
	</thead>
	<tbody>
		{% for cartproduct in cartobject.cartproduct_set.all %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'ecomapp:adminproductdetail' cartproduct.product.id %}">{{cartproduct.product.title}}</a></td>
			<td><a href="{% url 'ecomapp:adminproductdetail' cartproduct.product.id %}"><img src="{{cartproduct.product.image.url}}" alt="product" width="70px"></a></td>
			<td>{{cartproduct.rate}}</td>
			<td>{{cartproduct.quantity}}</td>
			<td>{{cartproduct.created_at.date}}</td>
			<td>{{cartproduct.subtotal}}</td>
		</tr>
		{% endfor %}
		<tr>
			<th colspan="6" class="text-right">Total: </th>
			<th>{{cartobject.total}}</th>
		</tr>	
		<tr><th>Ordered Date: </th></tr>
		<tr><th>Payment Method: </th></tr>
		<tr><th>Payment Date: </th></tr>
	</tbody>
</table>


{% endblock %}

templates/admintemplates/admincartlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Cart List page
{% endblock %}


{% block content %}
	<h3 class="text-success">All Carts</h3>

	<div class="row">
		<table class="table">
			<thead>
				<tr>
					<th>SN</th>
					<th>Cart ID</th>
					<th>Customer</th>
					<th>Total</th>
					<th>Order Status</th>
				</tr>
			</thead>

			<tbody>
				{% for cart in allcarts %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="{% url 'ecomapp:admincartdetail' cart.id %}">Cart ID: {{cart.id}}</a></td>
					<td>{{cart.customer}}</td>
					<td>{{cart.total}}</td>
					<td></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>


{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Home Page
{% endblock %}


{% block content %}
<h3>Admin Home Page</h3>
{% endblock %}

templates/admintemplates/adminorderdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Order Detail Page
{% endblock %}



{% block content %}

<h4>Order Detail of ID: {{orderobject.id}}</h4>
<div class="row">
	<div class="col">
		<table class="table">
			<thead>
				<tr>
					<th>SN</th>
					<th>Product</th>
					<th>Rate</th>
					<th>Quantity</th>
					<th>Subtotal</th>
				</tr>
			</thead>
			<tbody>
				{% for cartproduct in orderobject.cart.cartproduct_set.all %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{cartproduct.product.title}}</td>
					<td>{{cartproduct.rate}}</td>
					<td>{{cartproduct.quantity}}</td>
					<td>{{cartproduct.subtotal}}</td>
				

				</tr>
				{% endfor %}
			</tbody>			
		</table>
		
	</div>
	
</div>

{% endblock %}

templates/admintemplates/adminorderlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Order List
{% endblock %}

{% block content %}
	<h3 class="text-success">All Order</h3>

	<div class="row">
		<table class="table">
			<thead>
				<tr>
					<th>SN</th>
					<th>Cart ID</th>
					<th>Customer</th>
					<th>Total</th>
					<th>Order Status</th>
				</tr>
			</thead>

			<tbody>
				{% for order in allorders %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">Order ID: {{order.id}}</a></td>
					<td>{{order.customer}}</td>
					<td>{{order.total}}</td>
					<td></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

{% endblock %}

templates/admintemplates/adminproductdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Product Detail Page
{% endblock %}



{% block content %}

<h4> Product detail of {{productobject.title}} </h4>

<h4>Title: <span>{{productobject.title}}</span></h4>
<img src="{{productobject.image.url}}" alt="product" width="300px">
<h3>Stock Keeping Unit(SKU): {{productobject.sku}}</h3>
<h3>MRP: Rs.{{productobject.mrp}}</h3>
<h3>SP: Rs.{{productobject.sp}}</h3>
<h3>Registered Under Category: <span>{{productobject.category.title}}</span></h3>


{% endblock %}

templates/admintemplates/adminproductlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Product List
{% endblock %}

{% block content %}
	
	<h3 class="text-center text-success">***List Of All Products***</h3><hr><br>
		{% if page_obj.has_other_pages %}
		<ul class="pagination">
		    {% if page_obj.has_previous %}
		    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
		    {% else %}
		    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
		    {% endif %}
		    {% for n in page_obj.paginator.page_range %}
		        {% if page_obj.number == n %}
		            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
		        {% else %}
		            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
		        {% endif %}
		    {% endfor %}
		    {% if page_obj.has_next %}
		      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a></li>
		    {% else %}
		      <li class="page-item disabled"><span class="page-link">Next</span></li>
		    {% endif %}
		</ul>
	<div class="row">
		{% for product in allproducts %}
		<div class="col-3">
			<h4>{{product.title}}</h4>
			<img src="{{product.image.url}}" alt="product" width="120px">
			<h5>Price: {{product.sp}}</h5>
			<a href="{% url 'ecomapp:adminproductdetail' product.id %}" class="text-info">View Detail...</a>
		</div>
		{% endfor %}
{% endif %}
	</div>



{% endblock %}

templates/admintemplates/adminsignin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
	Ecom-Admin SignIn Page		
	</title>
</head>
<body class="container-fluid">

	
<div class="row">
	<div class="col-md-6 mx-auto">
		<h4>Admin Signin Form</h4><hr>
		<form method="post">
			{% if error %}
			<li class="text-danger">{{error}}</li>
			{% endif %}
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" name="Signin" class="btn btn-info">		
		</form>	
	</div>
</div>





</body>
</html>

templates/admintemplates/error.html
{% block content %}
	<h4>
		Error : {{error}}
	</h4>


{% endblock %}

templates/admintemplates/search.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Search Results
{% endblock %}


{% block content %}
<div class="row">
	<h3>Search Results On: "<span>{{request.GET.query}}</span>"</h3>
	<hr>
	<hr>
</div>

{% if allproducts.has_other_pages %}
<ul class="pagination">
	{% if allproducts.has_previous %}
	<li class="page-item"><a class="page-link" href="?page={{ allproducts.previous_page_number }}&query={{request.GET.query}}">Previous</a></li>
	{% else %}
	<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	{% endif %}
	{% for n in allproducts.paginator.page_range %}
		{% if allproducts.number == n %}
			<li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
		{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ n }}&query={{request.GET.query}}">{{n}}</a></li>
		{% endif %}
	{% endfor %}
	{% if allproducts.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ allproducts.next_page_number}}&query={{request.GET.query}}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
</ul>
{% endif %}
<div class="row">
	{% for search in allproducts %}
		<div class="col-md-3">
			<img class="card-img-top" src="{{ search.image.url }}" width="250" height="200">
			<div class="card-body bg-light text-center">
			<h5 class="card-title ">{{ search.title }}</h5>
			<p class="card-text mb-3 ">Price: Rs.{{ search.sp }}/-</p>
			<p>{{search.category.title}}</p>
			<a href="{% url 'ecomapp:adminproductdetail' search.id %}">view more</a>
			</div>
		</div>
		<hr>
		{% empty %}
		<div class="col-md-3">
			<p class="card-text mb-3 ">No results found</p>
		</div>
	{% endfor %}

</div>



{% endblock %}